version: "3"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: mcv-framework
    ports:
      - 80:80
    volumes:
      - .:/srv/app
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: mvc
      DB_USERNAME: app
      DB_PASSWORD: password
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    # Aug-2021 A Fix for Docker (Apple Silicon/M1 Preview) MySQL "no matching manifest for linux/arm64/v8 in the manifest list entries"
    # https://newbedev.com/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8-in-the-manifest-list-entries
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mvc
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379
