#  Generated by Hobo on 6/27/17



Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
	config.vm.provision :shell, path: "bootstrap.sh"
	config.vm.network :forwarded_port, host: 8080, guest: 80

    config.vm.provider "virtualbox" do |v| 
        # Give VM 1/4 of the Host Environments Memory 
        host = RbConfig::CONFIG['host_os']
        if host =~ /darwin/
            # sysctl returns Bytes and we need to convert to MB
            mem = `sysctl -n hw.memsize`.to_i / 1024
        elsif host =~ /linux/
            # meminfo shows KB and we need to convert to MB
            mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i 
        elsif host =~ /mswin|mingw|cygwin/
            # Windows code via https://github.com/rdsubhas/vagrant-faster
            mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
        end
        mem = mem / 1024 / 4
        v.customize ["modifyvm", :id, "--memory", mem]
    end
end
